[workspace]
authors = ["Nektarios Kalogridis <mail@nektarios.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "GrowNet"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.6.0.dev2025080505,<26"
